### ISSUE TITLE
Upgrade typescript definition

### ISSUE THREAD

**Issue by TrySound** [renatorib/react-powerplug#161]
There was a few changes and we need to upgrade typescript definitions.

Changes are in these commits
https://github.com/renatorib/react-powerplug/commit/4cfb56f62c44ba92a4c4d0439ece95734726f163
https://github.com/renatorib/react-powerplug/commit/e747c261fa8d952ef2076077aa30a4a34ac7bff2
https://github.com/renatorib/react-powerplug/commit/1e6f5b0054af3d1acd380309cff1f611ab5fd34d
https://github.com/renatorib/react-powerplug/commit/7cb56d02ade57e262d8b45c0f797560757f3f11d

/cc @theKashey @renatorib

**Comment by theKashey** [comment]
I heard about generation Flow from TS, or TS from Flow.
It will be great to have a single source of _types_.

**Comment by TrySound** [comment]
That's the point. Type systems are different. For example, typescript definitions exports all types even implementation details. This is not acceptable to me in flow where I carefully work with types as a part of api.

Generation will probably will work with generating definitions from less opinionated about javascript type systems like reason.

**Comment by theKashey** [comment]
> For example, typescript definitions exports all types even implementation details. 
Just split d.ts into 2 files, and, while types will be still visible for compiler, they will not be a part of autocomplete stuff.

**Comment by TrySound** [comment]
@theKashey I don't get, how omitting `export` can make types invisible for compiler? I thought it just some kind of convention "export everything and always".

**Comment by theKashey** [comment]
original d.ts
```js
export type InternalStuff = {};                              // oh! exposed internals
export type CoolStuff = { value : InternalStuff } // I need only this!!!
```
🤔🤔🤔🤔🤔🤔🤔🤔🤔

internals.d.ts
```js
export type InternalStuff = {};                            
```

original d.ts
```js
import {InternalStuff} from './internals.d.ts'; // not exported!
export type CoolStuff = { value : InternalStuff }
```
Bingo!

That's basically how d.ts looks like if generated from TS files - scattered across original modules, providing the same "import" experience.

**Comment by TrySound** [comment]
I don't get what's wrong with this.
```ts
type InternalStuff = {};
export type CoolStuff = { value : InternalStuff }
```
Why this tambourine dancing?

**Comment by TrySound** [comment]
Anyway, I want to release new rc to test form component in my app. Would be good to update ts before that.

**Comment by theKashey** [comment]
> I don't get what's wrong with this.

Also have no idea why linting is against it. I'll try to update typing in my first free time slot.

**Comment by everdimension** [comment]
I think you rushed a bit when you updated types.

Currently, not all components pass `reset` and `resetState` callbacks (i.e. [Focus](https://github.com/renatorib/react-powerplug/blob/v1.0.0/src/components/Focus.js), [Hover](https://github.com/renatorib/react-powerplug/blob/v1.0.0/src/components/Hover.js), maybe more)

But your typings say that they do: https://github.com/renatorib/react-powerplug/blob/v1.0.0/types/index.d.ts#L14

(because [FocusRender](https://github.com/renatorib/react-powerplug/blob/v1.0.0/types/index.d.ts#L57) has type of [RenderFn](https://github.com/renatorib/react-powerplug/blob/v1.0.0/types/index.d.ts#L14), and `RenderFn` extends [SharedProps](https://github.com/renatorib/react-powerplug/blob/v1.0.0/types/index.d.ts#L7-L10))

This is a mistake
