### ISSUE TITLE
What kind of components should this lib have?

### ISSUE THREAD

**Issue by lucasconstantino** [renatorib/react-powerplug#87]
Have you guys draw a line on what kind of components this lib should have? I have plenty of possible things that could come here and are already developed, but I'm unsure they fit this lib's purpose. Some:

_Promised_
```jsx
<Promised promise={ Promise.resolve('value') }>
  { (value, loading) => (
    loading ? 'loading...' : <div>Result: { value }</div>
  ) }
</Promised>
```

_MatchMedia_
```jsx
<MatchMedia breakpoints={ { small: '(max-width: 400px)', 'big': '(min-width: 401px)' } }>
  { match => (
    <div>
      I'm on { match === 'small' ? 'mobile' : 'desktop' }
    </div>
  ) }
</MatchMedia>
```

**Comment by TrySound** [comment]
I would prefer `react-measure` over media queries to isolate components.

Data loading is too complex problem for one component. There still will be suspense soon which is much more powerful.

**Comment by renatorib** [comment]
The idea was born in a pain of writing storybook stories for dumb components.
So, the first component ever was `Toggle`. 

Instead of creating a new class component just to control some UI states (I used to use recompose `withState`), it become much more simple:

```jsx
<Toggle>
  {({ on, toggle }) => (
    <CollapsableComponent onClick={toggle} opened={on}>
      ...
    </CollapsableComponent>
  )}
</Toggle>
```

Then I had the idea of creating components that coverage more usecases in the same problem. Now I had `State`, `Toggle`, `Counter`, `List`, etc...

After I published the powerplug and it made a relative success I realized that it could be used in other things besides storybook/related.

But I still have a general idea that the powerplug components should be 'autonomous' and provide the state when needed, and never rely on external state to work. I am still open to new ideas as long as they follow this concept and are simple, practice, plug and play.

**Comment by TrySound** [comment]
@renatorib Recompose maintainer is happy with powerplug too. :)

**Comment by renatorib** [comment]
To ask your question about `MatchMedia/Promised`. I believe that this `MatchMedia` is not so generic, and `Promised` maybe not simple (I'm not sure in that case)

**Comment by lucasconstantino** [comment]
I totally agree with the opinions on both `MatchMedia` and `Promised`, but my point here is not to suggest these components but rather discuss what should really be on the lib, in a broader perspective.

I remember when `recompose` first started that many people were arguing about the amount of options `recompose` provided, mostly due to the fact that most of the helpers can be easily built with the more generic ones. For instance, `mapProps` can be used to create `renameProps`, `withProps`, `flattenProp`, and a bunch other.

Another issue was that they created `renameProp` and `renameProps`, but decided not to have `mapProp` or `withProp`, which would be singular equivalents and even more functional based.

I guess we could find a way to encourage people to suggest new components for this tool-belt, but also make it more clear on what are the requirements for something to be considered eligible to be part of the lib.

Btw: if tree shaking comes into play, it won't really matter if the lib has a couple of components or hundreds, nor the overall size of the bundled version.

**Comment by renatorib** [comment]
I understand your point @lucasconstantino, and I totally agree too. 

I believe that there is still something very clear, although the points I have already clarified are a good clue.
For now it will pass through a filter of mine and the people who collaborate here, until we can have something more concrete.
But thank you very much for raising this topic, which in my view is extremely important.

<3
